"""
astro_project_sample_pipeline
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
from astro.table import Table, Metadata
import pandas as pd
import pendulum


@aql.run_raw_sql(conn_id="duckdb_default", task_id="sql_1", handler=lambda x: pd.DataFrame(x.fetchall(), columns=x.keys()))
def sql_1_func():
    return """
    
    """

@aql.dataframe(task_id="python_1")
def python_1_func():
    return

@dag(
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2023-05-23", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
)
def astro_project_sample_pipeline():
    sql_1 = sql_1_func()

    python_1 = python_1_func()

    python_1 << sql_1

dag_obj = astro_project_sample_pipeline()
